<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWs5Y+45qaC5Ya1');
$cfg_Cs[2]=array(1,1,1,'5YWs5Y+45LuL57uN');
$cfg_Cs[6]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[23]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[24]=array(23,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[26]=array(23,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[32]=array(24,1,1,'5p+l55yL55WZ6KiA');
$cfg_Cs[33]=array(0,17,1,'6KeG6aKR5bGV56S6');
$cfg_Cs[36]=array(0,1,1,'6YCa55+l5YWs5ZGK');
?>