<li class="p_show">
                        <div class="pic">
                            <a href='[field:arcurl/]'>
                                <img src='[field:picname/]'></a>
                        </div>
                        <div class="right">
                            <a href='[field:arcurl/]'>
                                <h3>[field:title/]</h3></a>
                            <p>
                            </p>
                            <a class="btn more" href='[field:arcurl/]'>了解更多 》</a>
                            <a class="btn book" href="[field:global.cfg_tmall/]">预订 》</a></div>
                    </li>