<li>
                                    <div class="pic">
                                        <a href='[field:arcurl/]'>
                                            <img src='[field:picname/]' width="197" height="132"></a>
                                    </div>
                                    <p>
                                        <a href='[field:arcurl/]'>[field:title/]</a></p>
                                </li>