<li>
                                        <p class="msgTheme">
                                            <b class="tit">[留言主题]：</b>[field:f1/]</p>
                                        <p class="msger">
                                            <b class="tit">[留言人]：</b>[field:f3 /]</p>
                                        <p class="msgTime">
                                            <b class="tit">[留言时间]：</b>2014-12-2 10:35:03</p>
                                        <div class="msgText">
                                            <b class="tit">[留言内容]：</b> [field:f6/]</div>
                                        <div class="msgReply">
                                            <b class="tit">[管理员回复]：</b>管理员回复</div></li>