<li>
                            <div class="pic">
                                <a href='[field:arcurl/]'>
                                    <img src='[field:picname/]'></a>
                            </div>
                            <a class="name" href='[field:arcurl/]'>[field:title/]</a>
                            <p>
                            </p>
                        </li>