<?php
$z[0]=Array("arcurl","",59,74);
$z[0][4]=array();
$z[1]=Array("picname","",123,139);
$z[1][4]=array();
$z[2]=Array("arcurl","",243,258);
$z[2][4]=array();
$z[3]=Array("title","",305,319);
$z[3][4]=array();
$z[4]=Array("pubdate","",371,418);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("description","",476,545);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"...\",200)";

?>