
<field:f1 itemname="留言主题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:f1>

<field:f2 itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:f2>

<field:f3 itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:f3>

<field:f4 itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:f4>

<field:f5 itemname="个人主页" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:f5>
