<?php
$z[0]=Array("arcurl","",60,75);
$z[0][4]=array();
$z[1]=Array("picname","",125,141);
$z[1][4]=array();
$z[2]=Array("arcurl","",247,262);
$z[2][4]=array();
$z[3]=Array("title","",310,324);
$z[3][4]=array();
$z[4]=Array("pubdate","",377,424);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("description","",484,553);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"...\",200)";

?>