<li class="clear">
                        <div class="pic">
                            <img src='[field:picname/]'>
                            <!--<p><img src="{dede:global.cfg_templets_skin/}/picture/yuding_img1.jpg"></p>--></div>
                        </a>
                        <div class="right">
                            <div class="tit">[field:title/]</div>
                            <span>[field:shorttitle/]</span>
                            <p>
                            </p>
                            <h3>[field:jg/]</h3>
                            <div class="btn">
                                <a class="tit">点击购票
                                    <a>
                                        <dl>
                                            <dd>
                                                <a href="[field:tmall/]" target="_blank">
                                                    <img src="{dede:global.cfg_templets_skin/}/picture/yuding_img3.jpg"></a></dd>
                                            <dd>
                                                <a href="[field:go/]" target="_blank">
                                                    <img src="{dede:global.cfg_templets_skin/}/picture/yuding_img4.jpg"></a>
                                            </dd>
                                            <dd>
                                                <a href="[field:city/]" target="_blank">
                                                    <img src="{dede:global.cfg_templets_skin/}/picture/yuding_img5.jpg"></a>
                                            </dd>
                                        </dl>
                            </div>
                            <div class="share1">分享到：
                                <div class="bdsharebuttonbox">
                                    <a href="#" class="bds_more" data-cmd="more"></a>
                                    <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                                    <a title="分享到QQ好友" href="#" class="bds_sqq" data-cmd="sqq"></a>
                                    <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                                    <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                                </div>
                            </div>
                            <script>window._bd_share_config = {
                                    "common": {
                                        "bdSnsKey": {},
                                        "bdText": "",
                                        "bdMini": "2",
                                        "bdMiniList": false,
                                        "bdPic": "",
                                        "bdStyle": "0",
                                        "bdSize": "16"
                                    },
                                    "share": {}
                                };
                                with(document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~ ( - new Date() / 36e5)];</script>
                        </div>
                    </li>