<dd class="clear">
                                            <a href='[field:arcurl/]'>
                                                <img src='[field:picname/]' width="87" height="59"></a>
                                            <div class="text">
                                                <a class="tit" href='[field:arcurl/]'>[field:title/]</a>
                                                <p>
                                                </p>
                                            </div>
                                        </dd>