<?php
$z[0]=Array("global","",119,151);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",245,277);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("type","<a href='[field:typelink /]'>[field:typename /]</a>",613,698);
$z[2][4]=array();
$z[2][4]['typeid']="1";
$z[3]=Array("global","",854,886);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("sql"," [field:description/] ",1003,1100);
$z[4][4]=array();
$z[4][4]['sql']="Select description from dede_arctype where id=1";
$z[5]=Array("channel","\r\n                                        <a href='javascript:return false;' class=''>[field:typename/]</a>",1154,1312);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['typeid']="1";
$z[6]=Array("type","<a href='[field:typelink /]'>[field:typename /]</a>",1761,1846);
$z[6][4]=array();
$z[6][4]['typeid']="6";
$z[7]=Array("type","<a href='[field:typelink /]'>[field:typename /]</a>",1999,2085);
$z[7][4]=array();
$z[7][4]['typeid']="36";
$z[8]=Array("type","<a href='[field:typelink /]'>[field:typename /]</a>",2254,2340);
$z[8][4]=array();
$z[8][4]['typeid']="33";
$z[9]=Array("type","<a href='[field:typelink /]'>[field:typename /]</a>",2513,2599);
$z[9][4]=array();
$z[9][4]['typeid']="23";
$z[10]=Array("channel","\r\n                                    <dd>\r\n                                        <a href='[field:typeurl/]'>\r\n                                            <p>[field:typename/]</p>\r\n                                            <div class=\"pic\">\r\n                                                <img src='[field:arcpic/]'></div>\r\n                                        </a>\r\n                                    </dd>\r\n									",2774,3261);
$z[10][4]=array();
$z[10][4]['type']="son";
$z[10][4]['row']="3";
$z[10][4]['typeid']="23";

?>