<?php
$z[0]=Array("global","",91,123);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("arclist","\n                        <li>\n                            <a href='[field:arcurl/]'>\n                                <img src='[field:picname/]'>\n                                <p>[field:title/]</p>\n                            </a>\n                        </li>\n						",359,722);
$z[1][4]=array();
$z[1][4]['row']="1000";
$z[1][4]['pagesize']="8";
$z[1][4]['titlelen']="20";
$z[1][4]['typeid']="18";
$z[1][4]['orderby']="rand";

?>