<?php
$z[0]=Array("global","",93,125);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("arclist","\r\n                        <li>\r\n                            <a href='[field:arcurl/]'>\r\n                                <img src='[field:picname/]'>\r\n                                <p>[field:title/]</p>\r\n                            </a>\r\n                        </li>\r\n						",366,736);
$z[1][4]=array();
$z[1][4]['row']="1000";
$z[1][4]['pagesize']="8";
$z[1][4]['titlelen']="20";
$z[1][4]['typeid']="18";
$z[1][4]['orderby']="rand";

?>